/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Icetask1;

public class App {

    

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            String StudentNumber = JOptionPane.showInputDialog("Enter student number:");
            
        }
    }
}
